---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: prowlarr
  values:
    controllers:
      prowlarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.3.6@sha256:da6b1f914ad22778c347d554a59b6e40110f654b40528c8de516616382db5148
            env:
              PROWLARR__SERVER__PORT: &port 80
              PROWLARR__UPDATE__BRANCH: develop
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 588Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Prowlarr
          gethomepage.dev/group: Media
          gethomepage.dev/icon: prowlarr.png
          gethomepage.dev/href: https://prowlarr.${SECRET_DOMAIN_0}
          gethomepage.dev/description: Indexer Manager
          gethomepage.dev/widget.type: prowlarr
          gethomepage.dev/widget.url: http://prowlarr.default.svc.cluster.local
          gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_PROWLARR_KEY}}" }}'
        hostnames: ["prowlarr.${SECRET_DOMAIN_0}"]
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
