---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 0 */12 * * *
  kopia:
    accessModes:
      - ${VOLSYNC_ACCESSMODE:=ReadWriteOnce}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /Kubernetes-Volumes/Kopia
            server: 192.168.200.30
    parallelism: 2
    repository: ${APP}-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: ${VOLSYNC_STORAGECLASS:=rook-ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=rook-ceph-block}
