---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: seerr
  values:
    controllers:
      seerr:
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
            env:
              LOG_LEVEL: info
              PORT: &port 80
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: [ALL]}
              readOnlyRootFilesystem: true

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - seerr.${SECRET_DOMAIN_0}
          - request.${SECRET_DOMAIN_0}
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config
      config-cache:
        type: nfs
        server: 192.168.200.30
        path: /Kubernetes-Volumes/default-seerr-cache
        globalMounts:
          - path: /app/config/cache
      tmp:
        type: emptyDir
