---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-sdk-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: bitwarden-sdk-server-secret
    template:
      data:
        token: '{{ .key }}'
  data:
    - secretKey: key
      remoteRef:
        key: bitwarden-eso-machine-key
