---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sonarr
  values:
    controllers:
      sonarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.17@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c
            env:
              SONARR__SERVER__PORT: &port 80
              SONARR__UPDATE__BRANCH: develop
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 15m
                memory: 443Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: &nfsServer 192.168.200.30
        path: /Media
        globalMounts:
          - path: /media
      mediacover:
        type: nfs
        server: *nfsServer
        path: /Kubernetes-Volumes/default-sonarr-mediacover
        globalMounts:
          - path: /config/MediaCover
      tmp:
        type: emptyDir

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Sonarr
          gethomepage.dev/group: Media
          gethomepage.dev/icon: sonarr.png
          gethomepage.dev/href: https://tv.${SECRET_DOMAIN_0}
          gethomepage.dev/description: TV Shows Management
          gethomepage.dev/widget.type: sonarr
          gethomepage.dev/widget.url: http://sonarr.default.svc.cluster.local
          gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_SONARR_KEY}}" }}'
        hostnames: ["tv.${SECRET_DOMAIN_0}"]
        parentRefs:
          - name: envoy-external
            namespace: network

    service:
      main:
        ports:
          http:
            port: *port
