---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
components:
  - ../../components/alerts
  - ../../components/envsubst
resources:
  - ./namespace.yaml
  - ./cert-manager/fluxtomization.yaml
  - ./trust-manager/fluxtomization.yaml
