---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/alerts
  - ../../components/envsubst
resources:
  - ./namespace.yaml
  - ./cilium/fluxtomization.yaml
  - ./coredns/fluxtomization.yaml
  - ./descheduler/fluxtomization.yaml
  - ./generic-device-plugin/fluxtomization.yaml
  - ./intel-gpu-resource-driver/fluxtomization.yaml
  - ./k8tz/fluxtomization.yaml
  - ./kubernetes-replicator/fluxtomization.yaml
  - ./metrics-server/fluxtomization.yaml
  - ./reloader/fluxtomization.yaml
  - ./snapshot-controller/fluxtomization.yaml
