---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radicale
spec:
  targetNamespace: default
  interval: 1h
  prune: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: radicale
  path: ./cluster/apps/default/radicale/base
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cloudnative-pg-cluster
      namespace: database
    - name: volsync
      namespace: volsync-system
