---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: opencloud-secret
    template:
      data:
        OC_JWT_SECRET: "{{ .OC_JWT_SECRET }}"
        OC_SERVICE_ACCOUNT_ID: "{{ .OC_SERVICE_ACCOUNT_ID }}"
        OC_SERVICE_ACCOUNT_SECRET: "{{ .OC_SERVICE_ACCOUNT_SECRET }}"
        NOTIFICATIONS_SMTP_PASSWORD: "{{ .NOTIFICATIONS_SMTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: opencloud
