---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: opencloud
  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/opencloudeu/opencloud-rolling
              tag: 6.0.0
            command:
              - /bin/sh
              - -c
              - opencloud init || true; opencloud server
            env:
              NOTIFICATIONS_SMTP_HOST: smtp.gmail.com
              NOTIFICATIONS_SMTP_INSECURE: false
              NOTIFICATIONS_SMTP_PORT: "587"
              NOTIFICATIONS_SMTP_SENDER: OpenCloud Admin <admin@budimanjojo.com>
              NOTIFICATIONS_SMTP_USERNAME: budimanjojo@gmail.com
              OC_INSECURE: true
              OC_LOG_LEVEL: info
              PROXY_TLS: false
              OC_URL: https://files.${SECRET_DOMAIN_0}
              # we use external LDAP server so we don't have to deal with certificate maintenance chore
              OC_ADMIN_USER_ID: "d0b5e14f-98b2-3568-8a93-e9ea99c77a87"
              OC_EXCLUDE_RUN_SERVICES: idm
              OC_LDAP_BIND_DN: cn=opencloud_bind,ou=people,dc=home,dc=cluster
              OC_LDAP_INSECURE: true
              OC_LDAP_DISABLED_USERS_GROUP_DN: cn=opencloud_disabled,ou=groups,dc=home,dc=cluster
              OC_LDAP_DISABLE_USER_MECHANISM: group
              OC_LDAP_GROUP_BASE_DN: ou=groups,dc=home,dc=cluster
              OC_LDAP_GROUP_SCHEMA_ID: entryuuid
              OC_LDAP_SERVER_WRITE_ENABLED: true
              OC_LDAP_URI: ldap://lldap.security.svc.cluster.local:3890
              OC_LDAP_USER_BASE_DN: ou=people,dc=home,dc=cluster
              OC_LDAP_USER_SCHEMA_ID: entryuuid
              OC_LDAP_USER_FILTER: (&(objectClass=person)(memberOf=cn=opencloud_users,ou=groups,dc=home,dc=cluster))
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: opencloud
        ports:
          http:
            port: 9200
    route:
      app:
        hostnames:
          - files.${SECRET_DOMAIN_0}
        parentRefs:
          - name: envoy-external
            namespace: network
            port: 443
    persistence:
      data:
        type: nfs
        path: /Kubernetes-Volumes/opencloud
        server: 192.168.200.30
        globalMounts:
          - path: /etc/opencloud
            subPath: config
          - path: /var/lib/opencloud
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
