---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: opencloud
  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/opencloudeu/opencloud-rolling
              tag: 6.0.0
            command:
              - /bin/sh
              - -c
              - opencloud init || true; opencloud server
            env:
              NOTIFICATIONS_SMTP_HOST: smtp.gmail.com
              NOTIFICATIONS_SMTP_INSECURE: false
              NOTIFICATIONS_SMTP_PORT: "587"
              NOTIFICATIONS_SMTP_SENDER: OpenCloud Admin <admin@budimanjojo.com>
              NOTIFICATIONS_SMTP_USERNAME: budimanjojo@gmail.com
              OC_ADMIN_USER_ID: ""
              OC_INSECURE: true
              OC_LOG_LEVEL: info
              OC_URL: https://files.${SECRET_DOMAIN_0}
              PROXY_CSP_CONFIG_FILE_LOCATION: &csp /etc/opencloud/csp.yaml
              PROXY_TLS: false
              # Authelia OIDC
              # auto role assignment:
              # docs: https://docs.opencloud.eu/docs/next/admin/configuration/authentication-and-user-management/external-idp#automatic-role-assignments
              GRAPH_USERNAME_MATCH: none
              OC_EXCLUDE_RUN_SERVICES: idp
              OC_OIDC_ISSUER: https://auth.${SECRET_DOMAIN_0}
              PROXY_AUTOPROVISION_ACCOUNTS: true
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              PROXY_OIDC_REWRITE_WELLKNOWN: false
              PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
              PROXY_USER_OIDC_CLAIM: preferred_username
              PROXY_USER_CS3_CLAIM: username
              WEBFINGER_ANDROID_OIDC_CLIENT_ID: opencloudandroid
              WEBFINGER_ANDROID_OIDC_CLIENT_SCOPES: openid,profile,email,offline_access,groups
              WEBFINGER_DESKTOP_OIDC_CLIENT_ID: openclouddesktop
              WEBFINGER_DESKTOP_OIDC_CLIENT_SCOPES: openid,profile,email,offline_access,groups
              WEBFINGER_WEB_OIDC_CLIENT_ID: opencloudweb
              WEBFINGER_WEB_OIDC_CLIENT_SCOPES: openid,profile,email,groups
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: opencloud
        ports:
          http:
            port: 9200
    route:
      app:
        hostnames:
          - files.${SECRET_DOMAIN_0}
        parentRefs:
          - name: envoy-external
            namespace: network
            port: 443
    persistence:
      config-proxy:
        type: configMap
        name: opencloud-configmap
        globalMounts:
          - path: /etc/opencloud/proxy.yaml
            readOnly: true
            subPath: proxy.yaml
          - path: *csp
            readOnly: true
            subPath: csp.yaml
      data:
        type: nfs
        path: /Kubernetes-Volumes/opencloud
        server: 192.168.200.30
        globalMounts:
          - path: /etc/opencloud
            subPath: config
          - path: /var/lib/opencloud
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
