---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/alerts
  - ../../components/envsubst
resources:
  - ./namespace.yaml
  - ./autobrr/fluxtomization.yaml
  - ./bazarr/fluxtomization.yaml
  - ./clusterpolicies/fluxtomization.yaml
  - ./firefly-iii/fluxtomization.yaml
  - ./homeassistant/fluxtomization.yaml
  - ./homepage/fluxtomization.yaml
  - ./immich/fluxtomization.yaml
  - ./jellyfin/fluxtomization.yaml
  - ./mosquitto/fluxtomization.yaml
  - ./opencloud/fluxtomization.yaml
  - ./prowlarr/fluxtomization.yaml
  - ./qbittorrent/fluxtomization.yaml
  - ./qui/fluxtomization.yaml
  - ./radarr/fluxtomization.yaml
  - ./radicale/fluxtomization.yaml
  - ./recyclarr/fluxtomization.yaml
  - ./seerr/fluxtomization.yaml
  - ./shared/redisclusters/fluxtomization.yaml
  - ./sonarr/fluxtomization.yaml
  - ./tqm/fluxtomization.yaml
  - ./zigbee2mqtt/fluxtomization.yaml
