---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: lldap-secret
    template:
      data:
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_LDAP_BASE_DN: "{{ .LLDAP_LDAP_BASE_DN }}"
  dataFrom:
    - extract:
        key: lldap
