---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./cloudnative-pg/fluxtomization.yaml
  - ./cnpg-i-barman-cloud/fluxtomization.yaml
  - ./dragonfly-operator/fluxtomization.yaml
