---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: zigbee2mqtt
  values:
    controllers:
      zigbee2mqtt:
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.9.2@sha256:2a21bbf7a664a149024bbe1f776e3151f28ed9db15948270dcbffb89544a41f0
            env:
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "true"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              # mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.default.svc.cluster.local:1883
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
              # adapter
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: &usbdevice /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack
              ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER: "20"
              # frontend
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee.${SECRET_DOMAIN_0}
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 150Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
        pod:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_1a86_7523.present: "true"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      usb:
        type: hostPath
        hostPathType: CharDevice
        hostPath: *usbdevice
        globalMounts:
          - path: *usbdevice

    route:
      app:
        hostnames: [ "zigbee.${SECRET_DOMAIN_0}" ]
        parentRefs:
          - name: envoy-internal
            namespace: network

    service:
      app:
        ports:
          http:
            port: *port
