---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: ocis-configmap
    files:
      - proxy.yaml=./resources/proxy.yaml
      - csp.yaml=./resources/csp.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
