---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0-standalone-strict/resourceclaimtemplate-resource-v1.json
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: jellyfin
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly:
            deviceClassName: gpu.intel.com
