---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./client-certificate.yaml
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./objectstore.yaml
  - ./podmonitor.yaml
  - ./scheduledbackup.yaml
  - ./server-ca.yaml
  - ./client-certificate.yaml
