---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./authentication.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
    patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: not-used
        spec:
          postRenderers:
            patches:
              - target:
                  group: gateway.networking.k8s.io
                  kind: HTTPRoute
                patch:
                  - op: add
                    path: /metadata/annotations
                    value:
                      gatus.home-operations.com/endpoint: |-
                        conditions:
                          - "[STATUS] == any(401, 403)"
