---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tqm
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tqm
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      tqm:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        initContainers:
          retag: &container
            image:
              repository: ghcr.io/home-operations/tqm
              tag: 1.19.0@sha256:025ee0c0c8b75f4c7bffa90216eedb494b9884e092a47e9c49824fe63427808c
            args:
              - retag
              - qb
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: [ALL]}
              readOnlyRootFilesystem: true
        containers:
          clean:
            <<: *container
            args:
              - clean
              - qb
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: 0 22 * * 0
          suspend: true
        containers:
          main:
            <<: *container
            args:
              - orphan
              - qb
              - --dry-run

    defaultPodOptions:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /.config/tqm
      secret-file:
        name: tqm-secret
        type: secret
        globalMounts:
          - path: /.config/tqm/config.yaml
            subPath: config.yaml
            readOnly: true
      downloads:
        type: nfs
        server: 192.168.200.30
        path: /Media
        globalMounts:
          - path: /downloads
            subPath: Downloads/qbittorrent
            readOnly: true
