---
clusterName: home-cluster
talosVersion: v1.12.3
kubernetesVersion: v1.35.2
endpoint: https://192.168.200.20:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
patches:
  - |-
    cluster:
      coreDNS:
        disabled: true
    machine:
      kubelet:
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options:
              - rbind
              - rshared
              - rw
  # change the owner and group of zigbee controller so I can run zigbee2mqtt as non root user
  - |-
    machine:
      udev:
        rules:
          - SUBSYSTEMS=="usb", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", OWNER="1000", GROUP="1000"
  - |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins."io.containerd.cri.v1.runtime"]
              cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
              device_ownership_from_security_context = true
nodes:
  - hostname: kmaster1
    ipAddress: 192.168.200.21
    controlPlane: true
    installDisk: /dev/nvme0n1
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.200.21/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.200.1
        vip:
          ip: 192.168.200.20
  - hostname: kmaster2
    ipAddress: 192.168.200.22
    controlPlane: true
    installDiskSelector:
      model: V-GEN12SM22AR256
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.200.22/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.200.1
        vip:
          ip: 192.168.200.20
  - hostname: kmaster3
    ipAddress: 192.168.200.23
    controlPlane: true
    installDiskSelector:
      model: SAMSUNG MZ27KM480
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.200.23/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.200.1
        vip:
          ip: 192.168.200.20
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915
  patches:
    - |-
      cluster:
        apiServer:
          extraArgs:
            feature-gates: MutatingAdmissionPolicy=true
            runtime-config: admissionregistration.k8s.io/v1beta1=true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
    - |-
      cluster:
        proxy:
          disabled: true
      machine:
        time:
          disabled: false
          servers:
            - 192.168.200.1
worker:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915-ucode
  patches:
    - |-
      machine:
        time:
          disabled: false
          servers:
            - 192.168.200.1
