---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
spec:
  targetNamespace: security
  components:
    - ../../../../components/postgres-database
  postBuild:
    substitute:
      APP: authelia
  interval: 1h
  prune: true
  path: ./cluster/apps/security/authelia/base
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: lldap
  wait: false
