---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-postgres-secret
stringData:
  username: ${DATABASE_OWNER:=${APP}}
  hostname: postgres-rw.database.svc
  port: "5432"
  dbname: ${APP}
  uri: postgresql://${DATABASE_OWNER:=${APP}}@postgres-rw.database.svc:5432/${APP}?sslmode=verify-full&sslcert=/var/run/secrets/postgres-certs/tls.crt&sslkey=/var/run/secrets/postgres-certs/tls.key&sslrootcert=/var/run/secrets/postgres-root-ca/ca.crt
  jdbc-uri: jdbc:postgresql://postgres-rw.database.svc:5432/${APP}?user=${DATABASE_OWNER:=${APP}}&sslmode=verify-full&sslcert=/var/run/secrets/postgres-certs/tls.crt&sslkey=/var/run/secrets/postgres-certs/tls.key&sslrootcert=/var/run/secrets/postgres-root-ca/ca.crt
