---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homeassistant
  values:
    controllers:
      homeassistant:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.4.3@sha256:328680ff068d032fed0b0f64c26bd474ae6983e25d633ac8debce858a4742698
            env:
              postgresql_uri:
                valueFrom:
                  secretKeyRef:
                    name: homeassistant-postgres-secret
                    key: uri
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 600Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: 8123

    route:
      app:
        hostnames: ["home.${SECRET_DOMAIN_0}"]
        parentRefs:

          - name: envoy-external
            namespace: network

    persistence:
      config:
        existingClaim: homeassistant
        globalMounts:
          - path: /config
      config-cache:
        server: 192.168.200.30
        path: /Kubernetes-Volumes/default-homeassistant-cache
        type: nfs
        globalMounts:
          - path: /config/.venv
      tmp:
        type: emptyDir
