---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: radarr
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.2.0.10390@sha256:be596a2f896fdf15077af027f44500f73e1f6fb7b450a6494b37dd25b7cc5927
            env:
              RADARR__SERVER__PORT: &port 80
              RADARR__UPDATE__BRANCH: develop
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: ${CONFIG_NFS_SERVER_IP_ADDRESS}
        path: /Media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Radarr
          gethomepage.dev/group: Media
          gethomepage.dev/icon: radarr.png
          gethomepage.dev/href: https://bazarr.${SECRET_DOMAIN_0}
          gethomepage.dev/description: Movies Management
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: http://radarr.default.svc.cluster.local
          gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_RADARR_KEY}}" }}'
        hostnames: ["movie.${SECRET_DOMAIN_0}"]
        parentRefs:
          - name: envoy-external
            namespace: network

    service:
      app:
        ports:
          http:
            port: *port
