---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  values:
    grafanaDashboard:
      enabled: true
      grafanaOperator:
        enabled: true
        matchLabels:
          grafana.internal/instance: grafana
    manager:
      image:
        repository: ghcr.io/dragonflydb/operator
    rbacProxy:
      enabled: false
    serviceMonitor:
      enabled: true
  # TODO: the default value needs to be removed
  # ref: https://github.com/dragonflydb/dragonfly-operator/issues/484
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: GrafanaDashboard
              group: grafana.integreatly.org
            patch: |
              - op: remove
                path: /spec/instanceSelector/matchLabels/dashboards
