---
name: Publish Kubernetes schemas

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-kubernetes-schemas.yaml

env:
  UV_SYSTEM_PYTHON: "1"

jobs:
  main:
    name: Publish Kubernetes schemas
    runs-on: home-cluster-runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        # yamllint disable-line rule:comments
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Install kubectl
        # yamllint disable-line rule:comments
        uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0

      - name: Install uv
        # yamllint disable-line rule:comments
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Setup Python
        # yamllint disable-line rule:comments
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14.x

      - name: Install Python dependencies
        run: uv pip install pyyaml

      - name: Run crd-extractor
        run: |
          curl -fsSL https://raw.githubusercontent.com/datreeio/CRDs-catalog/f3cdc86d7e26c959f2c366f19a29c5e5872bf9d6/Utilities/crd-extractor.sh -o crd-extractor.sh
          curl -fsSL https://raw.githubusercontent.com/datreeio/CRDs-catalog/f3cdc86d7e26c959f2c366f19a29c5e5872bf9d6/Utilities/openapi2jsonschema.py -o openapi2jsonschema.py
          chmod +x crd-extractor.sh && ./crd-extractor.sh

      - name: Setup Node
        # yamllint disable-line rule:comments
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.x

      - name: Publish schemas
        # yamllint disable-line rule:comments
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: /home/runner/.datree/crdSchemas
          command: pages deploy --project-name=kubernetes-schemas --branch main .
