---
name: YAML Lint

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        fetch-depth: 1
    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint.yaml
