---
name: YAML Lint

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        fetch-depth: 1
    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint.yaml
