---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authelia-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    template:
      templateFrom:
        - target: Data
          configMap:
            items:
              - key: configuration.yaml
                templateAs: Values
            name: authelia-config-tpl
  dataFrom:
    - extract:
        key: authelia
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden-secretsmanager
