---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./config/configuration.yaml
    name: authelia-config-tpl
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./referencegrant.yaml
